// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  JavaScript: [
    {type: 'autogenerated', dirName: 'JavaScript'}
  ]
};

module.exports = sidebars;
